steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'orchestrator/Dockerfile'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/art-chat-orchestrator:$SHORT_SHA'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/art-chat-orchestrator:latest'
      - '.'

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/art-chat-orchestrator'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - 'orchestrator/deploy-cloud-run.sh'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/art-chat-orchestrator:$SHORT_SHA'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/art-chat-orchestrator:$SHORT_SHA'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/art-chat-orchestrator:latest'

options:
  logging: CLOUD_LOGGING_ONLY
